Генератор публикаций
htmlacademy-nodejs/2096115-typoteka-3 pull request #3
Opened 2022-05-04 21:58 UTC by pbologan

2022-05-05 02:44 UTC, KletskovG requested changes

2022-05-05 02:44 UTC, KletskovG commented on src/service/cli/utils/utils.js
> +const getRandomInt = (min, max) => {
Кажется, тут забыл про 'use strict'

2022-05-05 02:44 UTC, KletskovG commented on src/service/cli/generate.js
> +  Array(count).fill({}).map(() => ({
Тут как раз можно обойтись без `.map()` и сразу передать этот коллбэк в `.fill()`

2022-05-05 08:16 UTC, pbologan commented on src/service/cli/generate.js
> +  Array(count).fill({}).map(() => ({
Попробовал перенести коллбэк функцию из `.map()` в `.fill()` - получаю массив с `null`. Если передаю объект в `.fill()`, то на выходе получается массив одинаковых объектов. Может я что-то неправильно делаю?)

> Тут как раз можно обойтись без `.map()` и сразу передать этот коллбэк в `.fill()`

2022-05-06 12:39 UTC, KletskovG commented on src/service/cli/generate.js
> +  Array(count).fill({}).map(() => ({
Тут можешь попробовать сделать еще такой вариант - 
```js
  Array.from({length: count}, callback)
```

По идее он должен сработать

Если не получится - то оставляй как есть

2022-05-06 13:37 UTC, merged